USE SCHEMA POC;

CREATE TABLE IF NOT EXISTS USER
(
   USER_ID VARCHAR
  ,USER_NAME VARCHAR  
  ,USER_CITY VARCHAR
  ,USER_PIN VARCHAR
);

--ALTER TABLE USER ADD USER_PIN VARCHAR;

ALTER TABLE USER ADD USER_ADDRESS VARCHAR;