BEGIN TRANSACTION;
CREATE OR REPLACE TABLE POC.CNBSNOWFLAKEDEMO
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);


CREATE OR REPLACE TABLE POC.CNBSNOWFLAKEDEMO-1
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

UPDATE POC.CUSTOMER1 SET LAST_NAME = 'KUMAR' WHERE LAST_NAME = 1;
INSERT INTO POC.CUSTOMER1 VALUES('RAJ', 'KUMAR');

CREATE SCHEMA POC

CREATE OR REPLACE TABLE POC.CNBSNOWFLAKEDEMO-2
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

COMMIT;