BEGIN TRANSACTION;
CREATE OR REPLACE TABLE POC.CNBSNOWFLAKEDEMO
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);


CREATE OR REPLACE TABLE POC.CNBSNOWFLAKEDEMO_1
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

UPDATE POC.CUSTOMER1 SET LAST_NAME = 'KUMAR' WHERE LAST_NAME = 1;
INSERT INTO POC.CUSTOMER1 VALUES('RAJ', 'KUMAR');



CREATE OR REPLACE TABLE POC.CNBSNOWFLAKEDEMO_2
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);

COMMIT;