USE SCHEMA POC;

CREATE OR REPLACE PROCEDURE SP_SCRIPTLOG
   @SCRIPTLOG_UUID VARCHAR
   @SCRIPTLOG_NAME VARCHAR 
AS
$$
BEGIN
  INSERT INTO SCRIPTLOG (SCRIPTLOG_UUID, SCRIPTLOG_NAME, SCRIPTLOG_CREATEDDATE)
  VALUES (@SCRIPTLOG_UUID, @SCRIPTLOG_NAME, CURRENT_DATE());
END;
$$
;