BEGIN TRANSACTION;
INSERT INTO POC.USER VALUES('RAM', 'kUMAR', 20);
INSERT INTO POC.USER VALUES('ASHOK', 'kUMAR', 25);
INSERT INTO POC.USER VALUES('VARUN', 'SHARMA', 40);
INSERT INTO POC.USER VALUES('RATISH', 'kUMAR', 40);
INSERT INTO POC.USER VALUES('GANESH', 'KAR', 30);
INSERT INTO POC.USER VALUES('ALANKAR', 'kUMAR', 35);
INSERT INTO POC.USER VALUES('RAJEEV', 'kUMAR', 40);
COMMIT;