BEGIN TRANSACTION;

INSERT INTO POC.USER VALUES('Raghu', 'Ram', 30);
INSERT INTO POC.USER VALUES('Rajesh', 'Sharma', 25);

CREATE TABLE POC.VEHICLE
(
   VEHICLE_ID INT
  ,VEHICLE_NAME VARCHAR
  ,VEHICLE_TYPE INT
);

CREATE TABLE POC.VEHICLE_1
(
   VEHICLE_1_ID INT
   VEHICLE_1_NAME VARCHAR
  ,VEHICLE_1_TYPE INT
);

CREATE TABLE POC.VEHICLE_2
(
   VEHICLE_2_ID INT
  ,VEHICLE_2_NAME VARCHAR
  ,VEHICLE_2_TYPE INT
);

COMMIT;